[package]
name = "payslip-renamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = "0.7.2"
pdf-extract = "0.6.3"
lopdf = "0.27.0"
regex = "1.5.4"
